/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicunto.gui;

/**
 *
 * @author internet
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblEmailFun = new javax.swing.JLabel();
        txtEmailFun = new javax.swing.JTextField();
        lblCpfFun = new javax.swing.JLabel();
        txtCpfFun = new javax.swing.JTextField();
        lblDataNasFun = new javax.swing.JLabel();
        txtDataNasFun = new javax.swing.JTextField();
        lblTelefoneFun = new javax.swing.JLabel();
        txtTelefoneFun = new javax.swing.JTextField();
        lblNomeFun = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        lblEnderecoFun = new javax.swing.JLabel();
        txtEnderecoFun = new javax.swing.JTextField();
        lblBairroFun = new javax.swing.JLabel();
        txtBairroFun = new javax.swing.JTextField();
        lblNFun = new javax.swing.JLabel();
        txtNFun = new javax.swing.JTextField();
        lblCepFun = new javax.swing.JLabel();
        txtCepFun = new javax.swing.JTextField();
        lblCidadeFun = new javax.swing.JLabel();
        txtCidadeFun = new javax.swing.JTextField();
        lblEstadoFun = new javax.swing.JLabel();
        txtEstadoFun = new javax.swing.JTextField();
        lblCelularFun = new javax.swing.JLabel();
        txtCelularFun = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        lblTituloFun = new javax.swing.JLabel();
        lblDtAdmFun = new javax.swing.JLabel();
        txtDtAdmFun = new javax.swing.JTextField();
        lblSetor = new javax.swing.JLabel();
        txtSetorFun = new javax.swing.JTextField();
        btnCadFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 239, 231));

        lblEmailFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmailFun.setForeground(new java.awt.Color(108, 44, 21));
        lblEmailFun.setText("E-mail");

        txtEmailFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblCpfFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCpfFun.setForeground(new java.awt.Color(108, 44, 21));
        lblCpfFun.setText("CPF");

        txtCpfFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCpfFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblDataNasFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDataNasFun.setForeground(new java.awt.Color(108, 44, 21));
        lblDataNasFun.setText("Data de nascimento");

        txtDataNasFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDataNasFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblTelefoneFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTelefoneFun.setForeground(new java.awt.Color(108, 44, 21));
        lblTelefoneFun.setText("Telefone");

        txtTelefoneFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblNomeFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeFun.setForeground(new java.awt.Color(108, 44, 21));
        lblNomeFun.setText("Nome");

        txtNomeFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblEnderecoFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEnderecoFun.setForeground(new java.awt.Color(108, 44, 21));
        lblEnderecoFun.setText("Endereço");

        txtEnderecoFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEnderecoFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblBairroFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblBairroFun.setForeground(new java.awt.Color(108, 44, 21));
        lblBairroFun.setText("Bairro");

        txtBairroFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairroFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblNFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNFun.setForeground(new java.awt.Color(108, 44, 21));
        lblNFun.setText("Nº");

        txtNFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblCepFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCepFun.setForeground(new java.awt.Color(108, 44, 21));
        lblCepFun.setText("CEP");

        txtCepFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCepFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblCidadeFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCidadeFun.setForeground(new java.awt.Color(108, 44, 21));
        lblCidadeFun.setText("Cidade");

        txtCidadeFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCidadeFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblEstadoFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEstadoFun.setForeground(new java.awt.Color(108, 44, 21));
        lblEstadoFun.setText("Estado");

        txtEstadoFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEstadoFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblCelularFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCelularFun.setForeground(new java.awt.Color(108, 44, 21));
        lblCelularFun.setText("Celular");

        txtCelularFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCelularFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnFechar.setText("X");
        btnFechar.setBorder(null);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblTituloFun.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloFun.setText("Cadastro de Funcionário");

        lblDtAdmFun.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDtAdmFun.setForeground(new java.awt.Color(108, 44, 21));
        lblDtAdmFun.setText("Data de Admissão");

        txtDtAdmFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDtAdmFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblSetor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSetor.setForeground(new java.awt.Color(108, 44, 21));
        lblSetor.setText("Setor");

        txtSetorFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSetorFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        btnCadFunc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadFunc.setForeground(new java.awt.Color(108, 44, 21));
        btnCadFunc.setText("Cadastrar");
        btnCadFunc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 3, true));
        btnCadFunc.setContentAreaFilled(false);
        btnCadFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblTituloFun)
                        .addGap(249, 249, 249)
                        .addComponent(btnFechar))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCepFun)
                                .addGap(51, 51, 51)
                                .addComponent(txtCepFun, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblEnderecoFun)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBairroFun)
                                        .addComponent(txtEnderecoFun))
                                    .addGap(18, 18, 18)
                                    .addComponent(lblNFun)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNFun, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblNomeFun)
                                    .addGap(42, 42, 42)
                                    .addComponent(txtNomeFun))
                                .addComponent(lblBairroFun, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblCidadeFun)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEstadoFun)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEstadoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmailFun)
                                        .addComponent(lblCpfFun))
                                    .addGap(38, 38, 38)
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmailFun)
                                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(txtCpfFun, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDataNasFun)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDataNasFun, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSetor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(lblTelefoneFun)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCelularFun))
                                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(lblDtAdmFun)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDtAdmFun, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(218, 218, 218)))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCelularFun, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSetorFun, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFechar))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTituloFun)))
                .addGap(51, 51, 51)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFun)
                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoFun)
                    .addComponent(lblNFun)
                    .addComponent(txtNFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairroFun)
                    .addComponent(txtBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeFun)
                    .addComponent(txtCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoFun))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCepFun)
                    .addComponent(txtCepFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailFun)
                    .addComponent(txtEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfFun)
                    .addComponent(txtCpfFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNasFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNasFun))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneFun)
                    .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelularFun)
                    .addComponent(txtCelularFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtAdmFun)
                    .addComponent(txtDtAdmFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSetorFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose() ;
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncActionPerformed

    }//GEN-LAST:event_btnCadFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblBairroFun;
    private javax.swing.JLabel lblCelularFun;
    private javax.swing.JLabel lblCepFun;
    private javax.swing.JLabel lblCidadeFun;
    private javax.swing.JLabel lblCpfFun;
    private javax.swing.JLabel lblDataNasFun;
    private javax.swing.JLabel lblDtAdmFun;
    private javax.swing.JLabel lblEmailFun;
    private javax.swing.JLabel lblEnderecoFun;
    private javax.swing.JLabel lblEstadoFun;
    private javax.swing.JLabel lblNFun;
    private javax.swing.JLabel lblNomeFun;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JLabel lblTelefoneFun;
    private javax.swing.JLabel lblTituloFun;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtBairroFun;
    private javax.swing.JTextField txtCelularFun;
    private javax.swing.JTextField txtCepFun;
    private javax.swing.JTextField txtCidadeFun;
    private javax.swing.JTextField txtCpfFun;
    private javax.swing.JTextField txtDataNasFun;
    private javax.swing.JTextField txtDtAdmFun;
    private javax.swing.JTextField txtEmailFun;
    private javax.swing.JTextField txtEnderecoFun;
    private javax.swing.JTextField txtEstadoFun;
    private javax.swing.JTextField txtNFun;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtSetorFun;
    private javax.swing.JTextField txtTelefoneFun;
    // End of variables declaration//GEN-END:variables
}
