/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicunto.gui;

/**
 *
 * @author internet
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        txtNomeProd = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        lblNomeProd = new javax.swing.JLabel();
        btnFechar2 = new javax.swing.JButton();
        lblTituloProd = new javax.swing.JLabel();
        btnCadProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 239, 231));
        pnlPrincipal.setForeground(new java.awt.Color(108, 44, 21));

        txtNomeProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblDesc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(108, 44, 21));
        lblDesc.setText("Descrição");

        txtDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDesc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblQuant.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblQuant.setForeground(new java.awt.Color(108, 44, 21));
        lblQuant.setText("Quantidade");

        txtQuant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQuant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblNomeProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeProd.setForeground(new java.awt.Color(108, 44, 21));
        lblNomeProd.setText("Nome");

        btnFechar2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnFechar2.setText("X");
        btnFechar2.setBorder(null);
        btnFechar2.setContentAreaFilled(false);
        btnFechar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar2ActionPerformed(evt);
            }
        });

        lblTituloProd.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloProd.setText("Cadastro de Produto");

        btnCadProd.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCadProd.setForeground(new java.awt.Color(108, 44, 21));
        btnCadProd.setText("Cadastrar");
        btnCadProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 3, true));
        btnCadProd.setContentAreaFilled(false);
        btnCadProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblQuant)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblDesc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblNomeProd)
                                        .addGap(34, 34, 34)))
                                .addGap(27, 27, 27)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                                    .addComponent(txtNomeProd))))
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(lblTituloProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(btnFechar2)
                        .addGap(10, 10, 10))))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(btnCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar2)
                    .addComponent(lblTituloProd))
                .addGap(52, 52, 52)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProd))
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesc)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar2ActionPerformed
        this.dispose() ;
    }//GEN-LAST:event_btnFechar2ActionPerformed

    private void btnCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProdActionPerformed
        
    }//GEN-LAST:event_btnCadProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadProd;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblNomeProd;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblTituloProd;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
