/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicunto.gui;

/**
 *
 * @author internet
 */
public class Caixa extends javax.swing.JFrame {

    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblCodUsuCx = new javax.swing.JLabel();
        txtCodUsuCx = new javax.swing.JTextField();
        lblNomeUsuCx = new javax.swing.JLabel();
        lblCodCliCx = new javax.swing.JLabel();
        txtBairroFun = new javax.swing.JTextField();
        lbCodlProd = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        lblQuantProdCx = new javax.swing.JLabel();
        txtQuantProdCx = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        lblTituloCaixa = new javax.swing.JLabel();
        btnFinal = new javax.swing.JButton();
        lblNomeCliCx = new javax.swing.JLabel();
        txtNomeCliCx = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnExcItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdbDinheiro = new javax.swing.JRadioButton();
        lblQuantProdCx1 = new javax.swing.JLabel();
        rbdCtCred = new javax.swing.JRadioButton();
        rbdCtDeb = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 239, 231));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(10000, 10000));

        lblCodUsuCx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCodUsuCx.setForeground(new java.awt.Color(108, 44, 21));
        lblCodUsuCx.setText("Código Usuário");

        txtCodUsuCx.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodUsuCx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblNomeUsuCx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeUsuCx.setForeground(new java.awt.Color(108, 44, 21));
        lblNomeUsuCx.setText("Funcionário XPTO");

        lblCodCliCx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCodCliCx.setForeground(new java.awt.Color(108, 44, 21));
        lblCodCliCx.setText("Código Cliente");

        txtBairroFun.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairroFun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lbCodlProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbCodlProd.setForeground(new java.awt.Color(108, 44, 21));
        lbCodlProd.setText("Código Produto");

        txtCodProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        lblQuantProdCx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblQuantProdCx.setForeground(new java.awt.Color(108, 44, 21));
        lblQuantProdCx.setText("Quantidade");

        txtQuantProdCx.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQuantProdCx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        btnFechar.setText("X");
        btnFechar.setBorder(null);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblTituloCaixa.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTituloCaixa.setForeground(new java.awt.Color(252, 146, 109));
        lblTituloCaixa.setText("Caixa");

        btnFinal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFinal.setForeground(new java.awt.Color(108, 44, 21));
        btnFinal.setText("Finalizar Compra");
        btnFinal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 3, true));
        btnFinal.setContentAreaFilled(false);
        btnFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        lblNomeCliCx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeCliCx.setForeground(new java.awt.Color(108, 44, 21));
        lblNomeCliCx.setText("Nome ");

        txtNomeCliCx.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeCliCx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 2, true));

        btnAddItem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(108, 44, 21));
        btnAddItem.setText("Adicionar Item");
        btnAddItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 3, true));
        btnAddItem.setContentAreaFilled(false);
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnExcItem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnExcItem.setForeground(new java.awt.Color(108, 44, 21));
        btnExcItem.setText("Excluir Item");
        btnExcItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 44, 21), 3, true));
        btnExcItem.setContentAreaFilled(false);
        btnExcItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcItemActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 239, 231));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 142, 170), null));
        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód.", "Produto", "Quantidade", "Valor Unitário", "Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 188, 184));
        jScrollPane1.setViewportView(jTable1);

        rdbDinheiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbDinheiro.setForeground(new java.awt.Color(108, 44, 21));
        rdbDinheiro.setText("Dinheiro");
        rdbDinheiro.setContentAreaFilled(false);

        lblQuantProdCx1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblQuantProdCx1.setForeground(new java.awt.Color(108, 44, 21));
        lblQuantProdCx1.setText("Forma de Pagamento:");

        rbdCtCred.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbdCtCred.setForeground(new java.awt.Color(108, 44, 21));
        rbdCtCred.setText("Cartão de Crédito");
        rbdCtCred.setContentAreaFilled(false);

        rbdCtDeb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbdCtDeb.setForeground(new java.awt.Color(108, 44, 21));
        rbdCtDeb.setText("Cartão de débito");
        rbdCtDeb.setContentAreaFilled(false);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lbCodlProd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblCodCliCx)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)))
                                .addGap(60, 60, 60)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblQuantProdCx)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtQuantProdCx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNomeUsuCx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(lblNomeCliCx)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNomeCliCx, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCodUsuCx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodUsuCx, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnExcItem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                            .addComponent(lblQuantProdCx1)
                                            .addGap(18, 18, 18)
                                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbdCtCred)
                                                .addComponent(rdbDinheiro)
                                                .addComponent(rbdCtDeb))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblTituloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 939, Short.MAX_VALUE)
                        .addComponent(btnFechar)
                        .addContainerGap())))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblTituloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodUsuCx)
                    .addComponent(txtCodUsuCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeUsuCx))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCliCx)
                    .addComponent(lblNomeCliCx)
                    .addComponent(txtBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodlProd)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantProdCx)
                    .addComponent(txtQuantProdCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcItem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblQuantProdCx1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(rdbDinheiro)
                        .addGap(5, 5, 5)
                        .addComponent(rbdCtDeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbdCtCred)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcItemActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
       
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose() ;
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnExcItem;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFinal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCodlProd;
    private javax.swing.JLabel lblCodCliCx;
    private javax.swing.JLabel lblCodUsuCx;
    private javax.swing.JLabel lblNomeCliCx;
    private javax.swing.JLabel lblNomeUsuCx;
    private javax.swing.JLabel lblQuantProdCx;
    private javax.swing.JLabel lblQuantProdCx1;
    private javax.swing.JLabel lblTituloCaixa;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbdCtCred;
    private javax.swing.JRadioButton rbdCtDeb;
    private javax.swing.JRadioButton rdbDinheiro;
    private javax.swing.JTextField txtBairroFun;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtCodUsuCx;
    private javax.swing.JTextField txtNomeCliCx;
    private javax.swing.JTextField txtQuantProdCx;
    // End of variables declaration//GEN-END:variables
}
